data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "evaluation-segmentation-noise"
type: "FLAIR"
pathology: ["edema","non_enhancing"]
seed: 42
age_bins: [0, 58, 100]
lower_slice: 60
upper_slice: 130
reconstruction: 
  sampling_mask: "radial"
  models: 
    - network: "UNet"
      acceleration: 8
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/unet-8_20250106_102815/checkpoints/unet-8_20250106_102815_epoch_11_best.pth"
    - network: "UNet"
      acceleration: 16
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/unet-16_20250106_103029/checkpoints/unet-16_20250106_103029_epoch_7_best.pth"
    - network: "UNet"
      acceleration: 24
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/unet-24_20250106_112142/checkpoints/unet-24_20250106_112142_epoch_5_best.pth"
    - network: "GAN"
      acceleration: 8
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/UCSF-8/latest_net_G.pth"
    - network: "GAN"
      acceleration: 16
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/UCSF-16/latest_net_G.pth"
    - network: "GAN"
      acceleration: 24
      model_path: "/lotterlab/users/matteo/models/Noise/UCSF/UCSF-24/latest_net_G.pth"
segmentation:
    model_path: "/lotterlab/users/matteo/models/Noise/UCSF/segmentation_20250107_102327/checkpoints/segmentation_20250107_102327_epoch_38.pth"

