output_dir: './output'
output_name: 'gender-rebalanced-kspace'
save_interval: 1

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 5

data_root: '../../data/UCSF-PDGM/'
type: 'T2'
pathology: ["edema","non_enhancing"]
lower_slice: 60
upper_slice: 130
balancing: True

classifier_type: 'GenderBCEClassifier'  # Options: 'TTypeBCEClassifier', 'TGradeBCEClassifier', 'NLLSurvClassifier' 'AgeCEClassifier', 'GenderBCEClassifier'
network_type: 'ResNet18'  # Options: 'ResNet18', 'ResNet50'
seed: 31415
