data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "gradcam-unet-gender-rebalanced"
seed: 42
os_bins: 4 
age_bins: [0, 58, 100]
patient_ids: ["UCSF-PDGM-445", "UCSF-PDGM-253", "UCSF-PDGM-053", "UCSF-PDGM-076", "UCSF-PDGM-113", "UCSF-PDGM-318", "UCSF-PDGM-414", "UCSF-PDGM-133"]
reconstruction: 
  sampling_mask: "radial"
  type: "T2"
  pathology: ["edema","non_enhancing"]
  model: 
    - network: "UNet"
      model_path: "TODO"
classifiers:
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "../../models/gender-rebalanced_20241015_143831/checkpoints/gender-rebalanced_20241015_143831_epoch_1_best.pth"

