data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "gradcam-kspace"
seed: 42
os_bins: 4 
age_bins: [0, 58, 100]
patient_ids: ["UCSF-PDGM-445", "UCSF-PDGM-253", "UCSF-PDGM-053", "UCSF-PDGM-076", "UCSF-PDGM-113", "UCSF-PDGM-318", "UCSF-PDGM-414", "UCSF-PDGM-133"]
reconstruction: 
  sampling_mask: "radial"
  type: "T2"
  pathology: ["edema","non_enhancing"]
  model: 
    - network: "UNet"
      model_path: "../../models/unet/checkpoints/unet_20240927_164753_epoch_8_best.pth"
classifiers:
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "AgeCEClassifier"
      network: "ResNet18"
      model_path: "../../models/age-rebalanced-kspace_20241017_164023/checkpoints/age-rebalanced-kspace_20241017_164023_epoch_1_best.pth"
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "../../models/gender-rebalanced-kspace_20241017_164123/checkpoints/gender-rebalanced-kspace_20241017_164123_epoch_3_best.pth"

