data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "gradcam-rebalanced"
seed: 42
os_bins: 4 
age_bins: [0, 58, 100]
patient_ids: ["UCSF-PDGM-445", "UCSF-PDGM-253", "UCSF-PDGM-053", "UCSF-PDGM-076", "UCSF-PDGM-113", "UCSF-PDGM-318", "UCSF-PDGM-414", "UCSF-PDGM-133"]
reconstruction: 
  sampling_mask: "radial"
  type: "T2"
  pathology: ["edema","non_enhancing"]
  model: 
    - network: "UNet"
      model_path: "../../models/unet/checkpoints/unet_20240927_164753_epoch_8_best.pth"
classifiers:
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "TGradeBCEClassifier"
      network: "ResNet18"
      model_path: "../../models/tgrade-rebalanced_20241015_143438/checkpoints/tgrade-rebalanced_20241015_143438_epoch_6_best.pth"
    - type: "TTypeBCEClassifier"
      network: "ResNet18"
      model_path: "../../models/ttype-rebalanced_20241015_143317/checkpoints/ttype-rebalanced_20241015_143317_epoch_1_best.pth"
    - type: "NLLSurvClassifier"
      network: "ResNet18"
      model_path: "../../models/os-rebalanced_20241015_151610/checkpoints/os-rebalanced_20241015_151610_epoch_1_best.pth"
    - type: "AgeCEClassifier"
      network: "ResNet18"
      model_path: "../../models/age-rebalanced_20241015_151516/checkpoints/age-rebalanced_20241015_151516_epoch_1_best.pth"
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "../../models/gender-rebalanced_20241015_143831/checkpoints/gender-rebalanced_20241015_143831_epoch_1_best.pth"

