output_dir: './output'
output_name: 'unet-tgrade-mix'
save_interval: 1

num_epochs: 20
learning_rate: 0.0001
batch_size: 8
early_stopping_patience: 3

data_root: '../../data/UCSF-PDGM'
type: 'FLAIR'
lower_slice: 60
upper_slice: 130
age_bins: [0, 58, 100]

network_type: 'UNet'
sampling_mask: 'radial'
seed: 31415
